name: compitition_team_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Back/
    - assets/Biceps/
    - assets/chest/
    - assets/legs/
    - assets/shoulder/
    - assets/sounds/

  fonts:
    - family: Space_Mono
      fonts:
        - asset: assets/fonts/Space_Mono/SpaceMono-Regular.ttf

